language: php

php:
  - 5.6
  - 7.0
  - 7.1  
 
env:
  - DB=mysql
  
before_script:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - wp core download
  - wp core config --dbhost=wordpress.local --dbname=wordpress --dbuser=root --dbpass=root
  
script:
  - cd wp-content/themes
  - composer create-project wp-kit/theme=2.0.0 theme  --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - cd theme
  - composer update --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - wp kit vendor:publish
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
  
  
