language: php

php:
  - 5.6
  - 7.0
  - 7.1  
 
env:
  - DB=mysql
  
before_script:
  - wget http://wordpress.org/latest.tar.gz
  - tar xfz latest.tar.gz
  - mv wordpress/* ./
  - rmdir ./wordpress/
  - rm -f latest.tar.gz
  - sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" wp-config.php
  - sed -i "/DB_NAME/s/'[^']*'/'wordpress'/2" wp-config.php
  - sed -i "/DB_USER/s/'[^']*'/'root'/2" wp-config.php
  - sed -i "/DB_PASSWORD/s/'[^']*'/'root'/2" wp-config.php
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - wp package install git@github.com:wp-cli/db-command.git
  - wp db create 
  - wget https://github.com/ronaldbradford/schema/blob/master/wordpress.sql
  - wp db import wordpress.sql
  - rm -f wordpress.sql
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - mv composer.phar /usr/local/bin/composer
  
script:
  - cd wp-content/themes
  - composer create-project wp-kit/theme=2.0.0 theme  --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - cd theme
  - composer update --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - wp kit vendor:publish
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
  
  
