# Travis CI configuration file.
# @link https://travis-ci.org/

# Declare project language and PHP versions to test against.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
    - "7.1"
    - "7.0"
    - "5.6"

# Declare which versions of WordPress to test against.
# Also declare whether or not to test in Multisite.
env:
    # Trunk (current version in development is 4.4)
    # @link https://github.com/WordPress/WordPress
    - WP_VERSION=master WP_MULTISITE=0

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
    # Set up WordPress installation.
    - export WP_DEVELOP_DIR=/tmp/wordpress/
    - mkdir -p $WP_DEVELOP_DIR
    - theme_slug=$(basename $(pwd))
    - theme_dir=$WP_DEVELOP_DIR/wp-content/themes/$theme_slug
    - cd $WP_DEVELOP_DIR
    # GET WP CLI
    - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    - chmod +x wp-cli.phar
    - sudo mv wp-cli.phar /usr/local/bin/wp
    - wp core download
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    - wp config create --dbname=wordpress_test --dbuser=root
    - wp core install --url="http://localhost"  --title="Your Blog Title" --admin_user="admin" --admin_password="admin" --admin_email="admin@admin.com"
    - cd ..
    - mv $theme_slug $theme_dir
    # Hop into themes directory.
    - cd $theme_dir

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
    # Search theme for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - composer update --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    # Additional non-compulsory packages
    - composer require wp-kit/tgmpa-integration wp-kit/vc-integration wp-kit/acf-integration wp-kit/magic-meta wp-kit/flash
    - sed -i '16iWPKit\Integrations\Tgmpa\TgmpaServiceProvider::class, WPKit\Integrations\Vc\VisualComposerServiceProvider::class, WPKit\Integrations\Acf\AcfServiceProvider::class, Illuminate\Filesystem\FilesystemServiceProvider::class, Illuminate\Session\SessionServiceProvider::class, WPKit\Flash\FlashServiceProvider::class,' resources/config/providers.config.php
    - wp kit vendor:publish
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
